import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

// Where uploaded product images actually live on disk. Defaults to a folder
// inside the repo for local dev convenience (gitignored - see .gitignore).
// Production MUST set UPLOADS_DIR to an absolute path OUTSIDE the
// git-managed app directory (see deploy/README.md) so a redeploy - which
// re-clones or `git clean`s the app folder - never wipes uploaded images.
const UPLOADS_DIR = process.env.UPLOADS_DIR ? path.resolve(process.env.UPLOADS_DIR) : path.join(process.cwd(), 'uploads');

const ALLOWED_TYPES = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
};

const MAX_BYTES = 8 * 1024 * 1024; // 8MB

export function isAllowedImageType(mimeType) {
  return Object.prototype.hasOwnProperty.call(ALLOWED_TYPES, mimeType);
}

export function maxUploadBytes() {
  return MAX_BYTES;
}

export function getUploadsDir() {
  return UPLOADS_DIR;
}

// Resolves a DB-stored (or requested) relative path to an absolute path
// inside UPLOADS_DIR, refusing anything that would escape it. Relative
// paths are never accepted from an untrusted client for writes - only ever
// generated by saveProductImage below - but the serving route
// (/api/uploads/[...path]) does take one from the URL, so this is the one
// choke point both go through.
export function resolveUploadPath(relativePath) {
  const safeSuffix = path.normalize(relativePath).replace(/^([.]{2}(\/|\\|$))+/, '');
  const base = UPLOADS_DIR + path.sep;
  const full = path.resolve(UPLOADS_DIR, safeSuffix);
  if (full !== UPLOADS_DIR && !full.startsWith(base)) return null;
  return full;
}

// Saves a single uploaded file under uploads/products/<generated-name> - the
// generated name (never the client's original filename) is what avoids path
// traversal and filename collisions. Returns the relative path to store in
// the DB (e.g. "products/<uuid>.jpg").
export async function saveProductImage(buffer, mimeType) {
  const ext = ALLOWED_TYPES[mimeType];
  if (!ext) throw new Error('Unsupported image type');
  const dir = path.join(UPLOADS_DIR, 'products');
  await fs.mkdir(dir, { recursive: true });
  const filename = `${crypto.randomUUID()}.${ext}`;
  await fs.writeFile(path.join(dir, filename), buffer);
  return `products/${filename}`;
}

export async function deleteProductImage(relativePath) {
  const full = resolveUploadPath(relativePath);
  if (!full) return;
  await fs.unlink(full).catch(() => {}); // already-gone is fine
}
